### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by steve13durant** [drewdru/seasonsNNetwork#1]
could you tell me which dataset you use to train this model?

**Comment by drewdru** [comment]
Hi ^w^
I used random images from google and my dataset wasn't big enough, but NN works with this:
https://send.firefox.com/download/ad66e939fe6c287f/#TJjI2XJtfLWQMDJU0OHDBQ

if the link expired, you could ask me in the Telegram: @DrewDru

**Comment by steve13durant** [comment]
Thank you~
